# Generated by Django 4.2.11 on 2024-05-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business_Contacts",
            fields=[
                ("BC_ID", models.AutoField(primary_key=True, serialize=False)),
                ("HS_ID", models.CharField(max_length=255)),
                ("BC_FName", models.CharField(max_length=255)),
                ("BC_LName", models.CharField(max_length=255)),
                ("BC_Email", models.EmailField(max_length=255)),
                ("BC_Company_Name", models.CharField(max_length=255)),
                ("BC_Industry", models.CharField(max_length=255)),
                ("BC_Active", models.BooleanField(default=True)),
                ("BC_Job_Title", models.CharField(max_length=255)),
                ("BC_Phone", models.CharField(max_length=20)),
                ("BC_Post_Code", models.CharField(max_length=10)),
                ("BC_Street_Address", models.CharField(max_length=255)),
                ("BC_Created", models.DateTimeField(auto_now_add=True)),
                ("BC_Last_Updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Premium_network_contacts",
            fields=[
                ("PNM_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PNM_NumPicks", models.IntegerField(default=0)),
                ("PNM_Active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="OLGA_matches",
            fields=[
                ("OM_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PNM_ID", models.CharField(max_length=255)),
                ("OLGA_MatchDate", models.DateTimeField()),
                (
                    "BC_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mamo_app.business_contacts",
                    ),
                ),
            ],
        ),
    ]
